[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="gpucode-analyzer"
version="0.1"
requires-python=">= 3.9"
authors = [
        {name="Sreepathi Pai", email="sree@cs.rochester.edu"},
]
description="A generic framework for analyzing GPU code at the assembly level"
license="MIT"

[project.scripts]
gca-buildcfg="gpucodeanalyzer.buildcfg:main"
gca-skelcfg="gpucodeanalyzer.skeletonizer:main"
gca-classcfg="gpucodeanalyzer.classifier:main"
gca-bbcount="gpucodeanalyzer.bbcount:main"
gca-cfg2c="gpucodeanalyzer.cfg2c:main"
gca-slice="gpucodeanalyzer.slice:main"