#!/usr/bin/env python3

import json

def compare(src, dst):

    missing = set(src['class'].keys()) - set(dst['class'].keys())
    extra = set(dst['class'].keys()) - set(src['class'].keys())

    diff = {}
    for x in src['class']:
        if x not in dst['class']: continue
        if src['class'][x] != dst['class'][x]:
            diff[x] = (src['class'][x], dst['class'][x],
                       (src['class'][x] - dst['class'][x]))

    for x in missing:
        diff[x] = (src['class'][x], 0, src['class'][x])

    for x in extra:
        diff[x] = (0, dst['class'][x], -dst['class'][x])

    return missing, extra, diff

def main():
    import argparse

    p = argparse.ArgumentParser(description="Compare counts generated by gca-bbcount.")
    p.add_argument("base", help="Base counts to compare with")
    p.add_argument("comparison", nargs="+", help="Compare against")

    args = p.parse_args()

    with open(args.base, "r") as f:
        base = json.load(fp=f)

    for c in args.comparison:
        with open(c, "r") as f:
            comp = json.load(fp=f)

        missing, extra, diff = compare(base, comp)
        print("===>", c, "vs", args.base)
        if len(missing) or len(extra) or len(diff):
            if missing: print("ONLY IN BASE", missing)
            if extra: print("ONLY IN COMPARISON", extra)
            for y in diff:
                print("    ", y, " ".join(str(x) for x in diff[y]))
        else:
            print("    ", "identical")

if __name__ == "__main__":
    main()
